export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const SET_CURR_JOB = "SET_CURR_JOB";
export const SHOW_MORE_JOBS_SUCCESS = "SHOW_MORE_JOBS_SUCCESS";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";