export const GET_MY_JOBS_SUCCESS = 'GET_ALL_MY_JOBS_SUCCESS';
export const OPEN_JOB_MODAL = 'OPEN_JOB_MODAL';
export const CLOSE_JOB_MODAL = 'CLOSE_JOB_MODAL';
export const OPEN_EDITABLE = 'OPEN_EDITABLE';
export const OPEN_ADD_MODAL = 'OPEN_ADD_MODAL';
export const CLOSE_ADD_MODAL = 'CLOSE_ADD_MODAL';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';