export const GET_ALL_MY_JOBS_SUCCESS = 'GET_ALL_MY_JOBS_SUCCESS';
export const OPEN_JOB_MODAL = 'OPEN_JOB_MODAL';
export const CLOSE_JOB_MODAL = 'CLOSE_JOB_MODAL';
export const OPEN_EDITABLE = 'OPEN_EDITABLE';